Repository rgrgrg18/pastebin_cpy, pull requests merged in 2024-12, with the labels that each got.

#41 Add factory implementation
  src/reader/src/reader/factory.hpp
Labels: new code

#46 Reader scripts
  .github/workflows/build_reader.yaml
  .github/workflows/ut_reader.yaml
  src/reader/scripts/build.sh
  src/reader/scripts/config.sh
  src/reader/scripts/destroy.sh
  src/reader/scripts/rebuild.sh
  src/reader/scripts/run.sh
  src/reader/scripts/test.sh
Labels: infrastructure

#47 Common logic in shared test class in reader ut
  src/reader/src/reader/tests/ut/reader_tests.cpp
  src/reader/utility/random_paste_generator.cpp
  src/reader/utility/random_paste_generator.hpp
Labels: refactor

#48 Change random generator location and fix issues
  src/reader/paste_types.hpp
  src/reader/src/reader/tests/ut/CMakeLists.txt
  src/reader/src/reader/tests/ut/reader_tests.cpp
  src/reader/utility/CMakeLists.txt
  src/reader/utility/comparisition_paste_types.hpp
  src/reader/utility/random/CMakeLists.txt
  src/reader/utility/random/random_paste_generator.cpp
  src/reader/utility/random/random_paste_generator.hpp
Labels: refactor
